version: '3'

services:

  mosquitto:
    image: eclipse-mosquitto
    volumes:
     - ./mosquitto.conf:/mosquitto/config/mosquitto.conf 
    ports:
     - "1883:1883"
     - "9001:9001"
    networks:
      - iot
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
    networks:
      - iot

  telegraf:  
    image: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=n5mgRcIiA6u1S48B5fHGkTmRimARTP9nyit3_JSuSMw5mTCqWd_e0SfcqY15DNDgAal4LaAWO-wY6wUoa7uvGg==
      - INFLUXDB_ORG=ABC
    depends_on:
      - influxdb
    networks:
      - iot
  prometheus:
    image: bitnami/prometheus:latest
    restart: always
    depends_on:
      - influxdb
    environment:
      - TZ=UTC
    volumes:
      - ./prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
      - ./data/prometheus:/opt/bitnami/prometheus/data
    networks:
      - iot
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - iot
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - influxdb
      - prometheus


networks:
    iot:

