global:
        scrape_interval: 15s
scrape_configs:
      - job_name: "prometheus"
        static_configs:
                - targets:
                        - localhost:9090
      - job_name: "influxdb"
        static_configs:
                - targets:
                        - influxdb:8086
      - job_name: "telegraf"
        static_configs:
                - targets:
                        - telegraf:9273
